Repository CurtinFRC/2022-RapidReact, pull requests merged in 2022-01, with the labels that each got.

#6 Deploy component naming fix
  robot.gradle
Labels: enhancement

#8 Cj Patch (2022 Update wml-2022.1.0-beta)
  4788/src/main/cpp/Robot.cpp
  4788/src/main/include/RobotMap.h
  4788/src/vendordeps/Phoenix.json
  4788/src/vendordeps/REVRobotics.json
  4788/src/vendordeps/UDP_TransferNT-latest.json
  4788/src/vendordeps/WML-Core-latest.json
  4788/src/vendordeps/WML-Rev-latest.json
  4788/src/vendordeps/WPILibNewCommands.json
  4788/src/vendordeps/WPILibOldCommands.json
  4788/src/vendordeps/navx_frc.json
  4788/vendordeps/Phoenix.json
  4788/vendordeps/REVLib.json
  4788/vendordeps/UDP_TransferNT-Deps-latest.json
  4788/vendordeps/WML-Core-Deps-latest.json
  4788/vendordeps/WML-Core-latest.json
  4788/vendordeps/WML-Rev-Deps-latest.json
  4788/vendordeps/navx_frc.json
  azure-pipelines.yml
  build.gradle
  buildSrc/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  robot.gradle
  settings.gradle
  vendordeps/WPILibNewCommands.json
  vendordeps/WPILibOldCommands.json
Labels: enhancement

#11 Added space
  settings.gradle
Labels: enhancement

#14 Added intake code
  4788/src/main/cpp/Intake.cpp
Labels: documentation, enhancement

#20 Switch to Containers for Subs
  4788/src/main/cpp/ExampleElevator.cpp
  4788/src/main/cpp/Robot.cpp
  4788/src/main/include/ExampleElevator.h
Labels: bug

#21 Protobot Drivebase
  .vscode/launch.json
  .vscode/settings.json
  .wpilib/wpilib_preferences.json
  4788/src/main/cpp/Drivebase.cpp
  4788/src/main/cpp/ExampleElevator.cpp
  4788/src/main/cpp/Intake.cpp
  4788/src/main/cpp/Robot.cpp
  4788/src/main/cpp/Shooter.cpp
  4788/src/main/include/ControlMap.h
  4788/src/main/include/Drivebase.h
  4788/src/main/include/ExampleElevator.h
  4788/src/main/include/Robot.h
  4788/src/main/include/RobotMap.h
  4788/src/main/include/Shooter.h
  build.gradle
Labels: documentation, enhancement

#24 Cj patch lib update
  4788/vendordeps/UDP_TransferNT-latest.json
  4788/vendordeps/WML-Core-latest.json
  4788/vendordeps/WML-Rev-latest.json
Labels: enhancement

#22 Protobot climber
  4788/src/main/cpp/Climber.cpp
  4788/src/main/cpp/Main.cpp
  4788/src/main/cpp/Robot.cpp
  4788/src/main/include/Climber.h
  4788/src/main/include/ControlMap.h
Labels: documentation, enhancement

#26 integrated climber
  4788/src/main/cpp/Climber.cpp
  4788/src/main/cpp/Robot.cpp
  4788/src/main/include/Climber.h
  4788/src/main/include/ControlMap.h
  4788/src/main/include/Robot.h
  4788/src/main/include/RobotMap.h
Labels: documentation, enhancement
